#开发环境配置文件
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easydemodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  #Redis配置
  redis:
    #Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    # 连接池最大连接数（使用负值表示没有限制）
    jedis.pool.max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    jedis.pool.max-wait: -1ms
    # 连接池中的最大空闲连接
    jedis.pool.max-idle: 8
    # 连接池中的最小空闲连接
    jedis.pool.min-idle: 0

path:
  intercept: #/api/** #开发环境不进行拦截
  exclude: /api/user/**