#开发环境配置文件
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easydemodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false

path:
  intercept: #/api/** #开发环境不进行拦截
  exclude: /api/user/**