#测试环境配置文件
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easydemodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#日志文件配置
logging:
  level:
    root: info
  file:
    path: log/test/